remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Gamma Data Blog
author: Benjamin Roberts
description: Insights on data, analytics, generative AI, and business development.
email: benjamin@gamma-data.co.uk
github_username: robertsbd
show_excerpts: true
paginate: 5
