theme: minima
title: Gamma Data Blog
author: Benjamin Roberts
description: Insights on data, analytics, generative AI, and business development.
email: benjamin@gamma-data.co.uk
url: https://www.gamma-data.co.uk
baseurl: https://www.gamma-data.co.uk
github_username: robertsbd
show_excerpts: true
paginate: 5
