theme: minima
title: Gamma DnA Blog
author: Dr Benjamin Roberts
description: Data, AI, and business development.
email: benjamin@gamma-data.co.uk
github_username: robertsbd
show_excerpts: true
paginate: 5
